[project]
name = "napari-maskel"
license = "MIT"

version = "1.1.2"
description = "napari plugin for maskel: vessel skeletonization and feature extraction"

readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "maskel>=1.1.1,<2.0.0",
    "pandas",
    "napari[all]",
    "napari-assistant>=0.6.0",
    "napari-simpleitk-image-processing>=0.4.9",
    "napari-skimage>=0.6.0",
    "pyyaml>=6.0.3",
    "superqt",
]

[project.urls]
Homepage = "https://github.com/bionetslab/napari-maskel"
Repository = "https://github.com/bionetslab/napari-maskel"
Documentation = "https://bionetslab.github.io/napari-maskel/"
Changelog = "https://github.com/bionetslab/napari-maskel/releases"

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
]
docs = [
    "mkdocs>=1.6",
    "mkdocs-material>=9.5",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["napari_maskel*"]

[tool.setuptools.package-data]
napari_maskel = ["napari.yaml", "resources/*.png"]

[project.entry-points."napari.manifest"]
napari-maskel = "napari_maskel:napari.yaml"

[tool.pytest.ini_options]
markers = ["slow: big regression tests (skip with -m 'not slow')"]
